version: '3.4'

services:

  dispatcher:
    build:
      context: ./dispatcher
      args:
        version: 2019.12
        extra_packages: "linux-image-amd64 curl"
    container_name: worker_docker0
    hostname: worker0
    devices:
      - /dev/kvm # needed for QEMU
      - /dev/net/tun # needed for QEMU
    cap_add:
      - NET_ADMIN # needed for QEMU
    environment:
      - "DISPATCHER_HOSTNAME=--hostname=${DOCKER_WORKER_HOSTNAME}"
      - "LOGGER_URL=tcp://${LAVA_SERVER_HOSTNAME}:5555" # url to send logs
      - "MASTER_URL=tcp://${LAVA_SERVER_HOSTNAME}:5556" # url of lava master
      - "ENCRYPT=${LAVA_SERVER_ENCRYPT}"
      - "SOCKS_PROXY=${SOCKS_PROXY}"
      - "MASTER_CERT=${MASTER_CERT}"
      - "SLAVES_CERT=${SLAVES_CERT}"
    volumes:
      - '/boot:/boot:ro'
      - '/lib/modules:/lib/modules:ro'
      - '/dev/bus:/dev/bus:ro' # required for USB devices
      - '/dev/serial:/dev/serial:ro' # required for serial adapters
      - '/dev/disk:/dev/disk:ro' # required for SDMux
      - ./dispatcher/power-control/:/root/power-control
      - ./dispatcher/ssh/:/root/.ssh/
      - worker-http:/var/lib/lava/dispatcher/tmp
      - worker-tftp:/srv/tftp

  worker-webserver:
    build:
      context: ./httpd
    container_name: worker_httpd
    ports:
      - 80
    volumes:
      - worker-http:/var/lib/lava/dispatcher/tmp

  worker-tftpd:
    build:
      context: ./tftpd
    container_name: worker_tftpd
    ports:
        - 69:69/udp
    volumes:
      - worker-tftp:/srv/tftp

  ser2net:
    build:
      context: ./ser2net
    container_name: worker_ser2net
    privileged: true
    volumes:
      - ./ser2net/ser2net.conf:/etc/ser2net.conf
      - '/dev/serial:/dev/serial' # required for serial adapters
      - '/dev:/dev'
    devices: []
    ports:
      - 7101:7101

  worker-nfs:
    build:
      context: ./nfs
    privileged: true
    container_name: worker_nfs
    volumes:
      - ./nfs/ganesha.conf:/etc/ganesha/ganesha.conf
      - ./nfs/services:/etc/services
      - worker-http:/var/lib/lava/dispatcher/tmp
    ports:
      - 111:111
      - 111:111/udp
      - 2049:2049
      - 2049:2049/udp
      - 35543:35543

volumes:
  worker-http:
  worker-tftp:
  # lava-server job artifact volume
  joboutput:
    name: lava-server-job-output
